### PR TITLE
IDOCT: Research Evaluation Task

### PR DESCRIPTION
**Pull request by Shubhi-Jain98**
Hi All,
The below CTests include the rewritten tests and the tests validated for correctness and effectiveness. 

## CTest 1. org.apache.hadoop.net.TestNetUtils#testInvalidAddress 

**Param1: hadoop.security.dns.log-slow-lookups.threshold.ms**
- `2147483647` GOOD  | PASS
- `2147483648` BAD  | FAIL java.lang.NumberFormatException
- `-1` GOOD  | PASS
- `0` GOOD  | PASS

**Param2: hadoop.security.dns.log-slow-lookups.enabled**
- `false` GOOD | PASS
- `true` GOOD | PASS

**Param3: hadoop.rpc.socket.factory.class.default**
- `org.apache.hadoop.net.StandardSocketFactory` GOOD | PASS
- ` `   GOOD | PASS
- `org.apache.hadoop.net.NotStandardSocketFactory` BAD  | FAIL with java.lang.ClassNotFoundException: Class org.apache.hadoop.net.NotStandardSocketFactory not found
- `org.apache.hadoop.net.SocksSocketFactory` GOOD | PASS

## CTest 2. org.apache.hadoop.security.TestGroupsCaching# testExceptionCallingLoadWithoutBackgroundRefreshReturnsOldValue 

**Param1: hadoop.security.groups.cache.background.reload.threads**
- `1` = GOOD | PASS
- `90` = GOOD | PASS
- `hadoop.security.groups.cache.background.reload=false && -1` BAD | PASS
- `hadoop.security.groups.cache.background.reload=true && -1` BAD | FAIL with java.lang.IllegalArgumentException
- `hadoop.security.groups.cache.background.reload=false && 0` BAD | PASS
- `hadoop.security.groups.cache.background.reload=true && 0` BAD | FAIL with java.lang.IllegalArgumentException
- `2147483648` BAD | FAIL with java.lang.NumberFormatException

The CTest passes for bad values 0 and –1 as this configuration is not considered until hadoop.security.groups.cache.background.reload is set to true. On setting this hadoop.security.groups.cache.background.reload to true, the test gives expected behavior. 

**Param2: hadoop.user.group.static.mapping.overrides**
- `dr.who=;` GOOD | PASS
- `user1=group1;` GOOD | PASS
- `group1=group2;` GOOD | PASS
- `me=;` BAD | FAIL
- `user1=user2=group1` BAD | FAIL with org.apache.hadoop.HadoopIllegalArgumentException: Configuration hadoop.user.group.static.mapping.overrides is invalid

**Param3: hadoop.security.groups.negative-cache.secs**
- `30` GOOD | PASS
- `1000` GOOD | PASS
- `1` GOOD | PASS
- `99999999999999999999` BAD | FAIL java.lang.NumberFormatException

**Param4: hadoop.security.groups.cache.warn.after.ms**
- `5000` GOOD | PASS
- `1` GOOD | PASS
- `30` GOOD | PASS
- `-1` BAD | PASS
- `99999999999999999999` BAD | FAIL java.lang.NumberFormatException

Here, the test is passing on configuration values 0 and –1 because the value, warningDeltaMs, is used as a comparison in the code, **if (deltaMs > warningDeltaMs)**

**Param5: hadoop.security.groups.shell.command.timeout**
- `2s` GOOD | PASS
- `10s` GOOD | PASS
- `3m` GOOD | PASS
- `2j` BAD | FAIL java.lang.NumberFormatException

### Below are the two parameters added in the test:

**Added Param6: hadoop.security.groups.cache.secs**
- `1` GOOD | PASS
- `90` GOOD | PASS
- `300` GOOD | PASS
- `-1` BAD | FAIL java.lang.IllegalArgumentException: duration must be positive: -1000 MILLISECONDS
- `0` BAD | FAIL java.lang.IllegalArgumentException: duration must be positive: 0 MILLISECONDS

In this case, conf.setLong was sending default parameter value 1. The test was passing for non-negative values as well. Since time is a positive quantity, the value of the "hadoop.security.groups.cache.secs" parameter should be greater than 0. Hence, removed the default conf.setLong to fix the case. 

**Added Param7: hadoop.security.groups.cache.background.reload**
- `false` GOOD | PASS
- `true` GOOD | PASS

## CTest 3. org.apache.hadoop.io.compress.TestCodec#testGzipCodecWithParam 

**Param1: io.file.buffer.size**
- `8` GOOD | PASS
- `512` GOOD | PASS
- `4096` GOOD | PASS
- `-1` BAD | FAIL java.lang.IllegalArgumentException: Illegal bufferSize

## CTest 4. org.apache.hadoop.crypto.key.kms.TestKMSClientProvider#testSelectDelegationToken 

**Param1: hadoop.security.dns.log-slow-lookups.threshold.ms**
- `1` GOOD | PASS
- `1000` GOOD | PASS
- `2000` GOOD | PASS
- `-1` BAD | PASS
- `2147483648` BAD | FAIL java.lang.NumberFormatException

Here, the test is passing on configuration value –1 as well because here this value, slowLookupThresholdMs, is used a comparison in the code, **if (elapsedMs >= slowLookupThresholdMs)** 

**Param2: hadoop.security.dns.log-slow-lookups.enabled**
- `false` GOOD | PASS
- `true` GOOD | PASS

## CTest 5. org.apache.hadoop.security.TestShellBasedUnixGroupsMapping#testFiniteGroupResolutionTime 

**Param1: hadoop.security.groups.cache.background.reload.threads**
- `1` = GOOD | PASS
- `90` = GOOD | PASS
- `hadoop.security.groups.cache.background.reload=false && -1` BAD | PASS
- `hadoop.security.groups.cache.background.reload=true && -1` BAD | FAIL with java.lang.IllegalArgumentException
- `hadoop.security.groups.cache.background.reload=false && 0` BAD | PASS
- `hadoop.security.groups.cache.background.reload=true && 0` BAD | FAIL with java.lang.IllegalArgumentException
- `2147483648` BAD | FAIL with java.lang.NumberFormatException

**Param2: hadoop.security.groups.cache.secs**
- `1` GOOD | PASS
- `90` GOOD | PASS
- `300` GOOD | PASS
- `-1` BAD | FAIL java.lang.IllegalArgumentException: duration must be positive: -1000 MILLISECONDS
- `0` BAD | FAIL java.lang.IllegalArgumentException: duration must be positive: 0 MILLISECONDS

**Param3: hadoop.user.group.static.mapping.overrides**
- `dr.who=;` GOOD | PASS
- `user1=group1;` GOOD | PASS
- `me=;` GOOD | PASS
- `user1=user2=group1` BAD | FAIL with org.apache.hadoop.HadoopIllegalArgumentException: Configuration hadoop.user.group.static.mapping.overrides is invalid

**Param4: hadoop.security.groups.cache.background.reload**
- `false` GOOD | PASS
- `true` GOOD | PASS

**Param5: hadoop.security.groups.negative-cache.secs**
- `30` GOOD | PASS
- `1000` GOOD | PASS
- `1` GOOD | PASS
- `9995696789999978889` BAD | FAIL java.lang.NumberFormatException

**Param6: hadoop.security.groups.cache.warn.after.ms**
- `5000` GOOD | PASS
- `1` GOOD | PASS
- `30` GOOD | PASS
- `-1` BAD | PASS
- `9995696789999978889` BAD | FAIL java.lang.NumberFormatException

Here, the test is passing on configuration values 0 and –1 as well because here this value, warningDeltaMs, is used a comparison in the code, **if (deltaMs > warningDeltaMs)**

### CODE REVIEW

**Comment by tianyin** [comment]
@Justin-Xiang could you help review the PR?

**Comment by Justin-Xiang** [comment]
Thank you for the PR. Great work!

I have tested all of them and there is only one problem on my side:

In Ctest2 Param2: hadoop.user.group.static.mapping.overrides:
  * me=;

 This should fail in this line of code:
```
assertThat(groups.getGroups("me").size()).isEqualTo(2);
```
You can check `parseStaticMapping()` method in `Groups.java`:
```java
String user = userToGroupsArray[0];
List<String> groups = Collections.emptyList();
  if (userToGroupsArray.length == 2) {
    groups = (List<String>) StringUtils
            .getStringCollection(userToGroupsArray[1]);
 }
staticUserToGroupsMap.put(user, groups);
```
Here, the("me", []) will be put into the `staticUserToGroupsMap`

Besides, you can also take a closer look at the `cacheGroupsAdd()` function.

Btw, I wonder how you test param like "user1=user2=group1" since this param has 2 "=", you may have to modify the `run_single_ctest.py` to inject this successfully.  You can also push changes in this file to this PR.

**Comment by Shubhi-Jain98** [comment]
Thank you for reviewing my PR. 
Pardon me; this is a mistake on my end. I rechecked the workflow, and yes, the test will fail for me=; I have incorporated this change.

For the "user1=user2=user3" value, I found that since the python script finds the index of first "=" so the script injects the whole argument after it as a value; here, "user1=user2=user3". I am attaching the screenshot of the logs.
run_single_test_Logs

**Comment by Justin-Xiang** [comment]
@tianyin  Yes, I think @Shubhi-Jain98 has corrected the mistake I mentioned so it's ok to merge this PR.  But it seems that I don't have the authority to merge PR.

**Review by Justin-Xiang — APPROVED** [review]

**Pull request merged**
