### PR TITLE
Research Evaluation Task + BAD|PASS and GOOD|FAIL investigations

### PR DESCRIPTION
**Pull request by Shubhi-Jain98**
This PR contains the reviewed changes of previous PRs.
1. https://github.com/xlab-uiuc/IDoCT/pull/8
2. https://github.com/xlab-uiuc/IDoCT/pull/10

Both the above PRs have incorrect SHA. I have incorporated the correct SHA.

### CODE REVIEW

**Comment by Shubhi-Jain98** [comment]
Hi @Alex-Lian , I removed these two configurations from the TestGroupsCaching file, so to populate their different values from ctest_metadata.csv. Therefore, I added these two in [param_unset_getter_map.json](https://github.com/xlab-uiuc/IDoCT/pull/23/files#diff-3e08f6f0e015dae17099b3d2d25604098d7c50bfceb1952ca16aa7c068b36b3c).

**Comment by Alex-Lian** [comment]
@Shubhi-Jain98 Thanks for the answer. Could you please do me a favor to resolve the conflicts? I will merge the PR then.

**Comment by Shubhi-Jain98** [comment]
Hi @Alex-Lian, I noticed that the comma was replaced with white spaces. I tried changing the delimiter from excel settings and also tried this command - "sed 's/,/ /g' ctest_metadata.csv > resultfile.csv", but the data is not displaying correctly in CSV format. Could you please guide me on what command you used?

**Comment by Alex-Lian** [comment]
@Shubhi-Jain98 The white spaces are `/t`. So I believe "sed 's/,//t/g' ctest_metadata.csv > resultfile.csv" should work.

**Comment by Shubhi-Jain98** [comment]
Hi @Alex-Lian, thanks for helping me with the command. The command was also updating the commas inside the strings. 
I missed the simple conversion of CSV to tab-separated files from inside Google Sheets. It gave the expected results. Would you please review it.

**Pull request merged**
